{
    "url": "https://api.github.com/repos/spack/spack/issues/12445",
    "repository_url": "https://api.github.com/repos/spack/spack",
    "labels_url": "https://api.github.com/repos/spack/spack/issues/12445/labels{/name}",
    "comments_url": "https://api.github.com/repos/spack/spack/issues/12445/comments",
    "events_url": "https://api.github.com/repos/spack/spack/issues/12445/events",
    "html_url": "https://github.com/spack/spack/issues/12445",
    "id": 481703876,
    "node_id": "MDU6SXNzdWU0ODE3MDM4NzY=",
    "number": 12445,
    "title": "Installation issue: faidx",
    "user": {
        "login": "omsai",
        "id": 166624,
        "node_id": "MDQ6VXNlcjE2NjYyNA==",
        "avatar_url": "https://avatars.githubusercontent.com/u/166624?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/omsai",
        "html_url": "https://github.com/omsai",
        "followers_url": "https://api.github.com/users/omsai/followers",
        "following_url": "https://api.github.com/users/omsai/following{/other_user}",
        "gists_url": "https://api.github.com/users/omsai/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/omsai/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/omsai/subscriptions",
        "organizations_url": "https://api.github.com/users/omsai/orgs",
        "repos_url": "https://api.github.com/users/omsai/repos",
        "events_url": "https://api.github.com/users/omsai/events{/privacy}",
        "received_events_url": "https://api.github.com/users/omsai/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 446616547,
            "node_id": "MDU6TGFiZWw0NDY2MTY1NDc=",
            "url": "https://api.github.com/repos/spack/spack/labels/build-error",
            "name": "build-error",
            "color": "ff3300",
            "default": false,
            "description": null
        }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 0,
    "created_at": "2019-08-16T17:12:59Z",
    "updated_at": "2019-08-17T03:41:32Z",
    "closed_at": "2019-08-17T03:41:32Z",
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "body": "`faidx` has multiple runtime errors.  PR incoming.\r\n\r\n### Steps to reproduce the issue\r\n\r\n```console\r\n$ spack install py-pyfaidx\r\n$ spack load -r py-pyfaidx\r\n$ faidx home/gjv11003/genomes/hg38_dm6_cat/hg38_dm6_cat.fa -i chromsizes > chr_sizes_hg38_dm6.txt\r\nTraceback (most recent call last):\r\n  File \"/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.4.0/py-pyfaidx-0.5.5.2-t7rhiwg7gulcfuhv3ejj7kz427dpatmt/bin/faidx\", line 6, in <module>\r\n    from pkg_resources import load_entry_point\r\nModuleNotFoundError: No module named 'pkg_resources'\r\n```\r\n\r\nIf I correct for that error by adding the `'run'` dependency of `py-setuptools` I see that the package is missing the `six` dependency required by upstream's setup.py:\r\n\r\nhttps://github.com/mdshw5/pyfaidx/blob/master/setup.py#L5\r\n\r\n```python-traceback\r\nTraceback (most recent call last):                                                                                                                                                             \r\n  File \"/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.4.0/py-pyfaidx-0.5.5.2-bsu2a67cknr7imh6xkj3yhqgw3lfkudg/bin/faidx\", line 6, in <module>                                            \r\n    from pkg_resources import load_entry_point                                                                                                                                                 \r\n  File \"/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.4.0/py-setuptools-41.0.1-6ll4vdwgfhpd5l7fhvu7wsct2mxvi5tz/lib/python2.7/site-packages/pkg_resources/__init__.py\", line 3241, in <mo\r\ndule>                                                                                                                                                                                          \r\n    @_call_aside                                                                                                                                                                               \r\n  File \"/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.4.0/py-setuptools-41.0.1-6ll4vdwgfhpd5l7fhvu7wsct2mxvi5tz/lib/python2.7/site-packages/pkg_resources/__init__.py\", line 3225, in _ca\r\nll_aside                                                                                                                                                                                       \r\n    f(*args, **kwargs)                                                                                                                                                                         \r\n  File \"/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.4.0/py-setuptools-41.0.1-6ll4vdwgfhpd5l7fhvu7wsct2mxvi5tz/lib/python2.7/site-packages/pkg_resources/__init__.py\", line 3254, in _in\r\nitialize_master_working_set                                                                                                                                                                    \r\n    working_set = WorkingSet._build_master()                                                                                                                                                   \r\n  File \"/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.4.0/py-setuptools-41.0.1-6ll4vdwgfhpd5l7fhvu7wsct2mxvi5tz/lib/python2.7/site-packages/pkg_resources/__init__.py\", line 583, in _bui\r\nld_master                                                                                                                                                                                      \r\n    ws.require(__requires__)                                                                                                                                                                   \r\n  File \"/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.4.0/py-setuptools-41.0.1-6ll4vdwgfhpd5l7fhvu7wsct2mxvi5tz/lib/python2.7/site-packages/pkg_resources/__init__.py\", line 900, in requ\r\nire                                                                                                                                                                                            \r\n    needed = self.resolve(parse_requirements(requirements))                                                                                                                                    \r\n  File \"/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.4.0/py-setuptools-41.0.1-6ll4vdwgfhpd5l7fhvu7wsct2mxvi5tz/lib/python2.7/site-packages/pkg_resources/__init__.py\", line 786, in reso\r\nlve                                                                                                                                                                                            \r\n    raise DistributionNotFound(req, requirers)                                                                                                                                                 \r\npkg_resources.DistributionNotFound: The 'six' distribution was not found and is required by pyfaidx\r\n```\r\n\r\n### Platform and user environment\r\n\r\nPlease report your OS here:\r\n```commandline\r\n$ uname -a \r\nLinux corelab2 4.15.0-55-generic #60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux\r\n$ lsb_release -d\r\nDescription:    Ubuntu 18.04.3 LTS\r\n``` \r\n",
    "performed_via_github_app": null
}