{
    "url": "https://api.github.com/repos/spack/spack/issues/22379",
    "repository_url": "https://api.github.com/repos/spack/spack",
    "labels_url": "https://api.github.com/repos/spack/spack/issues/22379/labels{/name}",
    "comments_url": "https://api.github.com/repos/spack/spack/issues/22379/comments",
    "events_url": "https://api.github.com/repos/spack/spack/issues/22379/events",
    "html_url": "https://github.com/spack/spack/issues/22379",
    "id": 834981088,
    "node_id": "MDU6SXNzdWU4MzQ5ODEwODg=",
    "number": 22379,
    "title": "Python shared object file not found",
    "user": {
        "login": "wadudmiah",
        "id": 10605090,
        "node_id": "MDQ6VXNlcjEwNjA1MDkw",
        "avatar_url": "https://avatars.githubusercontent.com/u/10605090?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/wadudmiah",
        "html_url": "https://github.com/wadudmiah",
        "followers_url": "https://api.github.com/users/wadudmiah/followers",
        "following_url": "https://api.github.com/users/wadudmiah/following{/other_user}",
        "gists_url": "https://api.github.com/users/wadudmiah/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/wadudmiah/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/wadudmiah/subscriptions",
        "organizations_url": "https://api.github.com/users/wadudmiah/orgs",
        "repos_url": "https://api.github.com/users/wadudmiah/repos",
        "events_url": "https://api.github.com/users/wadudmiah/events{/privacy}",
        "received_events_url": "https://api.github.com/users/wadudmiah/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 73908754,
            "node_id": "MDU6TGFiZWw3MzkwODc1NA==",
            "url": "https://api.github.com/repos/spack/spack/labels/bug",
            "name": "bug",
            "color": "fc2929",
            "default": true,
            "description": null
        },
        {
            "id": 1433532775,
            "node_id": "MDU6TGFiZWwxNDMzNTMyNzc1",
            "url": "https://api.github.com/repos/spack/spack/labels/triage",
            "name": "triage",
            "color": "ed9793",
            "default": false,
            "description": "The issue needs to be prioritized"
        }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 2,
    "created_at": "2021-03-18T15:50:43Z",
    "updated_at": "2021-03-18T15:54:34Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "I have the following configuration (`~/.spack/packages.yaml`) for using an existing installation of Python:\r\n```\r\npackages:\r\n  python:\r\n    externals:\r\n    - spec: python@3.7.3\r\n      modules: [python/3.7.3]\r\n```\r\nWhen I try to install `py-numpy` using:\r\n```\r\n$ spack install py-numpy%intel@19.0.3 ^python@3.7.3\r\n```\r\nI get the following error message\r\n```\r\n==> No binary for py-numpy-1.20.1-cqq3qwdmz2cjaxa3g5ri5jdmru44hrlg found: installing from source\r\n/local/software/python/3.7.3/bin/python3.7: error while loading shared libraries: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory\r\n==> Error: ProcessError: Command exited with status 127:\r\n    '/local/software/python/3.7.3/bin/python3.7' '-c' 'from distutils.sysconfig import get_config_var; print(get_config_var('\"'\"'LIBDIR'\"'\"'))'\r\n/local/software/python/3.7.3/bin/python3.7: error while loading shared libraries: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory\r\n```\r\nThe module file `python/3.7.3` configures `LD_LIBRARY_PATH` to point to the shared object file. Using the `--dirty` flag doesn't raise this error message when the module file `python/3.7.3` is loaded. \r\n\r\n",
    "performed_via_github_app": null
}