{
    "url": "https://api.github.com/repos/spack/spack/issues/3728",
    "repository_url": "https://api.github.com/repos/spack/spack",
    "labels_url": "https://api.github.com/repos/spack/spack/issues/3728/labels{/name}",
    "comments_url": "https://api.github.com/repos/spack/spack/issues/3728/comments",
    "events_url": "https://api.github.com/repos/spack/spack/issues/3728/events",
    "html_url": "https://github.com/spack/spack/issues/3728",
    "id": 219878863,
    "node_id": "MDU6SXNzdWUyMTk4Nzg4NjM=",
    "number": 3728,
    "title": "Improve error message when package name is not consistent with Spack's conventions",
    "user": {
        "login": "JavierCVilla",
        "id": 4431174,
        "node_id": "MDQ6VXNlcjQ0MzExNzQ=",
        "avatar_url": "https://avatars.githubusercontent.com/u/4431174?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/JavierCVilla",
        "html_url": "https://github.com/JavierCVilla",
        "followers_url": "https://api.github.com/users/JavierCVilla/followers",
        "following_url": "https://api.github.com/users/JavierCVilla/following{/other_user}",
        "gists_url": "https://api.github.com/users/JavierCVilla/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/JavierCVilla/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/JavierCVilla/subscriptions",
        "organizations_url": "https://api.github.com/users/JavierCVilla/orgs",
        "repos_url": "https://api.github.com/users/JavierCVilla/repos",
        "events_url": "https://api.github.com/users/JavierCVilla/events{/privacy}",
        "received_events_url": "https://api.github.com/users/JavierCVilla/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 73908754,
            "node_id": "MDU6TGFiZWw3MzkwODc1NA==",
            "url": "https://api.github.com/repos/spack/spack/labels/bug",
            "name": "bug",
            "color": "fc2929",
            "default": true,
            "description": null
        }
    ],
    "state": "open",
    "locked": false,
    "assignee": {
        "login": "alalazo",
        "id": 4199709,
        "node_id": "MDQ6VXNlcjQxOTk3MDk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/4199709?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/alalazo",
        "html_url": "https://github.com/alalazo",
        "followers_url": "https://api.github.com/users/alalazo/followers",
        "following_url": "https://api.github.com/users/alalazo/following{/other_user}",
        "gists_url": "https://api.github.com/users/alalazo/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/alalazo/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/alalazo/subscriptions",
        "organizations_url": "https://api.github.com/users/alalazo/orgs",
        "repos_url": "https://api.github.com/users/alalazo/repos",
        "events_url": "https://api.github.com/users/alalazo/events{/privacy}",
        "received_events_url": "https://api.github.com/users/alalazo/received_events",
        "type": "User",
        "site_admin": false
    },
    "assignees": [
        {
            "login": "alalazo",
            "id": 4199709,
            "node_id": "MDQ6VXNlcjQxOTk3MDk=",
            "avatar_url": "https://avatars.githubusercontent.com/u/4199709?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/alalazo",
            "html_url": "https://github.com/alalazo",
            "followers_url": "https://api.github.com/users/alalazo/followers",
            "following_url": "https://api.github.com/users/alalazo/following{/other_user}",
            "gists_url": "https://api.github.com/users/alalazo/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/alalazo/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/alalazo/subscriptions",
            "organizations_url": "https://api.github.com/users/alalazo/orgs",
            "repos_url": "https://api.github.com/users/alalazo/repos",
            "events_url": "https://api.github.com/users/alalazo/events{/privacy}",
            "received_events_url": "https://api.github.com/users/alalazo/received_events",
            "type": "User",
            "site_admin": false
        }
    ],
    "milestone": null,
    "comments": 9,
    "created_at": "2017-04-06T12:14:10Z",
    "updated_at": "2018-04-14T10:51:16Z",
    "closed_at": null,
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "body": "Trying to install a new own package in local (probably wrong created by myself) I got this trace error:\r\n\r\n```\r\nTraceback (most recent call last):\r\n  File \"/my/path/spack/bin/spack\", line 220, in <module>\r\n    main(sys.argv)\r\n  File \"/my/path/spack/bin/spack\", line 216, in main\r\n    _main(args, unknown)\r\n  File \"/my/path/spack/bin/spack\", line 183, in _main\r\n    return_val = command(parser, args)\r\n  File \"/mnt/my/path/spack/lib/spack/spack/cmd/install.py\", line 317, in install\r\n    specs = spack.cmd.parse_specs(args.package, concretize=True)\r\n  File \"/mnt/my/path/spack/lib/spack/spack/cmd/__init__.py\", line 116, in parse_specs\r\n    spec.concretize()  # implies normalize\r\n  File \"/mnt/my/path/spack/lib/spack/spack/spec.py\", line 1681, in concretize\r\n    self._expand_virtual_packages(),\r\n  File \"/mnt/my/path/spack/lib/spack/spack/spec.py\", line 1598, in _expand_virtual_packages\r\n    spec)\r\n  File \"/mnt/my/path/spack/lib/spack/spack/concretize.py\", line 113, in choose_virtual_or_external\r\n    candidates = self._valid_virtuals_and_externals(spec)\r\n  File \"/mnt/my/path/spack/lib/spack/spack/concretize.py\", line 87, in _valid_virtuals_and_externals\r\n    if is_spec_buildable(cspec):\r\n  File \"/mnt/my/path/spack/lib/spack/spack/package_prefs.py\", line 239, in is_spec_buildable\r\n    allpkgs = get_packages_config()\r\n  File \"/mnt/my/path/spack/lib/spack/spack/package_prefs.py\", line 53, in get_packages_config\r\n    if spack.repo.is_virtual(pkg_name)]\r\n  File \"/mnt/my/path/spack/lib/spack/spack/repository.py\", line 347, in is_virtual\r\n    return pkg_name in self.provider_index\r\n  File \"/mnt/my/path/spack/lib/spack/spack/repository.py\", line 233, in provider_index\r\n    self._provider_index.merge(repo.provider_index)\r\n  File \"/mnt/my/path/spack/lib/spack/spack/repository.py\", line 652, in provider_index\r\n    self._update_provider_index()\r\n  File \"/mnt/my/path/spack/lib/spack/spack/repository.py\", line 646, in _update_provider_index\r\n    self._provider_index.to_yaml(new)\r\n  File \"/mnt/my/path/spack/lib/spack/llnl/util/lock.py\", line 312, in __exit__\r\n    if self._as.__exit__(type, value, traceback):\r\n  File \"/mnt/my/path/spack/lib/spack/spack/file_cache.py\", line 152, in __exit__\r\n    raise value\r\nTypeError: exceptions must be old-style classes or derived from BaseException, not str\r\n```\r\n\r\nThe last error comes from [here](https://github.com/LLNL/spack/blob/develop/lib/spack/spack/file_cache.py#L152). The trace suggests that `value` does not derive from an Exception class. Any idea what is happening?",
    "performed_via_github_app": null
}